JuliaIO/VideoIO.jl

src/util.jl
* No longer exported (or needed, seemingly) on v0.4
* Should be removed when support for v0.3 is dropped
cf: https://github.com/JuliaLang/julia/pull/11554, https://github.com/JuliaLang/julia/pull/1925
=> Qualify Base.start_reading from util.jl.  Fixes #54

src/ffmpeg/AVFormat/v55/avformat.jl
The error was:
```Julia
julia> f = VideoIO.openvideo("C:\\Users\\Sim\\Desktop\\aLP7m7v_460sv.mp4")
ERROR: MethodError: `convert` has no method matching convert(::Type{Ptr{Void}}, ::ASCIIString)
This may have arisen from a call to the constructor Ptr{Void}(...),
since type constructors fall back to convert methods.
Closest candidates are:
call{T}(::Type{T}, ::Any)
convert{T}(::Type{Ptr{T}}, ::UInt64)
convert{T}(::Type{Ptr{T}}, ::Int64)
...
in unsafe_convert at no file:382
in open_avinput at C:\Users\Sim\.julia\v0.4\VideoIO\src\avio.jl:212
in AVInput at C:\Users\Sim\.julia\v0.4\VideoIO\src\avio.jl:240
in AVInput at C:\Users\Sim\.julia\v0.4\VideoIO\src\avio.jl:225
in VideoReader at C:\Users\Sim\.julia\v0.4\VideoIO\src\avio.jl:368
in openvideo at …
```
=> this fixes another issue

src/avio.jl, test/avio.jl
* Works, but if we try to seek to the start in the middle of the file
there are a few frames remaining in the buffer, so it doesn't appear
to seek right away
=> Added seekstart (fixes #58)

deps/build.jl
Add the ffmpeg versions of the libraries because the libav versions available
on ubuntu 15.04 have not yet wrapped in VideoIO.
The ffmpeg libraries have been put first in the search order so that they'll be
found in preference, even if the user also has the libav versions installed.
This avoids a VideoIO crash at runtime when loading libraries which haven't
been wrapped yet.
=> Add ffmpeg package and library names for ubuntu 15.04

.travis.yml
Note that this uses older library versions, because the newer versions still need to be wrapped
=> Update to travis container infrastructure (take 2)

.gitignore, .travis.yml, REQUIRE, src/VideoIO.jl, src/avio.jl, src/testvideos.jl, test/avio.jl
This performs a couple of cleanup operations, and then updates for recent changes in the FixedPointNumbers/Images landscape. Most significantly, it decouples Video from Images itself. In this version I have it relying on ImageCore (a much smaller package), but even that isn't really necessary: I think the only function I use from there is `permuteddimsview`, and that's basically a wrapper around `Base.PermutedDimsArrays.PermutedDimsArray`. (I use a little bit more functionality for the tests.) If you'd prefer to decouple entirely, that would be fine.
It does change the output type returned by `read`: rather than an `Image` that wraps an `Array{UInt8}`, it returns a (lazy-transposed, i.e., permuted) `Array{RGB{N0f8}}`. As a consequence, this is a breaking change.
This bumps the minimum …
=> Update to the new Images

README.md, REQUIRE, src/VideoIO.jl, src/avio.jl, src/ffmpeg/AVCodecs/src/AVCodecs.jl, src/ffmpeg/AVDevice/src/AVDevice.jl, src/ffmpeg/AVFilters/src/AVFilters.jl, src/ffmpeg/AVFormat/src/AVFormat.jl, src/ffmpeg/SWResample/src/SWResample.jl, src/ffmpeg/SWScale/src/SWScale.jl, src/init.jl, src/libav/AVCodecs/src/AVCodecs.jl, src/libav/AVDevice/src/AVDevice.jl, src/libav/AVFormat/src/AVFormat.jl, src/libav/SWScale/src/SWScale.jl, src/version.jl
@kmsquire this is a PR into your branch from #124 
This isn't all the way done, but it's the best I can do right now, and I hope it's helpful. I fixed a few issues with 0.7+, but a few more remain:
The load path modifications weren't working for me on 0.7, so I changed all of the conditional import stuff to just use `include()` as usual. I think this is an improvement anyway, as the previous behavior was dangerous: if a user happened to create a package or module called `AVUtil`, then Julia might load their AVUtil or VideoIOs, depending on the load order, causing both packages to be broken. Using `include()` avoids the issue entirely. 
However, I noticed in the Readme a note that not all of the submodules are actually loaded and a suggestion that users can load them as they see fit. …
=> don't modify LOAD_PATH, and fix some deprecations on 0.7

src/VideoIO.jl, src/avio.jl
The test (and code) that was failing for precompilation was code that reads from a Julia `IOStream`.  Reading inputs directly with ffmpeg's own I/O functions was working fine.
In order to read from a Julia `IOStream`, we pass a callback function which fills a pre-allocated buffer with data from the stream.  The pointer to that callback has to be determined at runtime (in `__init__`), because the function location will change each time the program is run.
Cc: @timholy @ianshmean
=> Enable precompilation(!!!)

src/VideoIO.jl, src/avio.jl
* Camera device information is set in a number of global variables.  
* Because precompilation is now enabled, these need to be set in __init__()
=> Fix camera initialization

README.md, src/avio.jl
Hopefully a simple change to enable grayscale UInt8 based videos.
Also added an example for reading in a full video
=> Add `ColorTypes.gray` pixels

.travis.yml, Project.toml, appveyor.yml
Simple and seemingly logical change but worth checking CI for. Should significantly cut down on build time and complexity.
=> Remove ImageView as dep as not imported within package

README.md, src/VideoIO.jl
The current `ImageView` method seems to be broken, and this fixes it (for me at least).
It would be great to add play/pause, track, progress indicator, frame number, time etc, if those are easy to add now?
```julia
julia> using Makie, VideoIO
julia> VideoIO.playvideo("localpath/VideoIO.jl/videos/annie_oakley.ogg")
```
=> Replace ImageView video playback with Makie

src/info.jl, test/avio.jl
The correct duration of the "annie_oakley.ogg" movie is 24224200 **microsecond** (24.2242 seconds), not milliseconds. Otherwise it would have been 6 hours and 43 minutes and 44.2 seconds long..!
=> duration is in microseconds not milliseconds

src/VideoIO.jl
The plan is to remove this functionality in favor of external view functions in `Makie`, `ImageView` etc.
but for the moment, this should help usage
=> Add helper error messages if Makie not loaded before

src/VideoIO.jl
Reinstating platform specific camera name addressing that was missed out in a refactor during #163
=> Cam re-fix for mac and linux

.travis.yml, src/VideoIO.jl, src/avio.jl, src/init.jl, src/util.jl, test/avio.jl
With this, ffmpeg or ffprobe can be used externally like this (for instance to write a video) where the lib path for windows, linux and OSX needs to be set:
```julia
withenv("PATH" => VideoIO.libpath, "LD_LIBRARY_PATH" => VideoIO.libpath, "DYLD_LIBRARY_PATH" => VideoIO.libpath) do
open(`$(VideoIO.ffmpeg etc. etc. fname.mpeg`, "w") do out
for image in images
write(out, image)
end
end
end
```
=> Add tests for executables (ffmpeg & ffprobe)

src/ffmpeg/AVUtil/src/AVUtil.jl
There are some redefinitions occurring due to back-support of prior ffmpeg versions.
Given we're now fixed to ffmpeg 4.1, shall we remove all the older version support?
If not we can keep this as a simple PR to remove that redefinition
=> Tidying post BinaryProvider switch

README.md, deps/build.jl, examples/lossless_video_encoding_testing.jl, src/encoding.jl, test/avio.jl
Using `:color_range=>2` prevents the clamping of the GRAY8 pixel value range from 0-255 to 16-235
=> fix GRAY8 lossless encoding

.cirrus.yml
If you can enable https://github.com/marketplace/cirrus-ci on this repository (or perhaps all repos of the organisation), this PR allows testing on FreeBSD.  Note that failures on Julia 1.2 and nightly are expected
@ianshmean: probably you'll want to rebase #176 on master after this is merged
=> Add Cirrus CI script

README.md, src/encoding.jl
This means the simplest you'd do is:
```julia
encoder = prepareencoder(firstimage)
```
Which defaults to:
```julia
encoder = prepareencoder(firstimage;framerate=30,AVCodecContextProperties=[:priv_data => ("crf"=>"22","preset"=>"medium")],codec_name::String="libx264")
```
cc. @jessebett
=> optionals in prepareencoder()

src/VideoIO.jl, src/util.jl
there was an error in playvideo due to a type mismatch in the resolution tuple. I then also fixed it so it will work with different aspect ratios by adding a convenience function for retrieving the stored aspect ratio. The works nicely for me but check to see it's good for you too.
=> type error due to aspect ratio, help function for the aspect

test/avio.jl
Note that we should really add a video to the test videos that has a valid SAR that is not equal to 1. Such as [this](https://vision-group-temporary.s3.amazonaws.com//a.MTS) one, but that one won't stay at that url for much longer).
=> Add test for SAR

src/avio.jl, src/info.jl, test/avio.jl
@yakir12 Does this give what you want?
```
gettime(s::VideoReader;video_stream::Integer=1)
Return timestamp of current position in seconds.
```
i.e.
```julia
using VideoIO
f = VideoIO.testvideo("annie_oakley")
v = openvideo(f)
@show gettime(v)
seek(v,10.0)
@show gettime(v)
seek(v,15.0)
@show gettime(v)
```
gettime(v) = 0.0
gettime(v) = 9.943266666666668
gettime(v) = 14.948266666666669
=> Add `gettime()` to read approximate current position in seconds

src/encoding.jl
I noticed this was a bit heavy-handed, but didn't want to break things, so defaults to delete, but can be overridden
=> Make delete stream file optional in mux

Project.toml
There seems to have been breaking changes in FFMPEG.jl so I've locked compat to FFMPEG 0.2 (which it should've been before)
https://github.com/JuliaIO/FFMPEG.jl/issues/24
=> Lock ffmpeg.jl compat to 0.2

docs/src/reading.md, src/avio.jl, src/encoding.jl, src/testvideos.jl, test/avio.jl
The objective here is to provide the fastest way to 
1) skip through a frame 
2) skip through multiple frames 
3) get the most accurate & fastest count of remaining available frames
@rdeits @yakir12 What do you think about these?
I'll add tests if they look good
=> Add frame skip & frame count functions

docs/src/writing.md
These <br> tags are rendering as text on the docs page, not as a line break
=> remove <br> tags

src/encoding.jl, src/ffmpeg/AVUtil/src/AVUtil.jl, test/avio.jl
While ffmpeg allows the use of rational frame rates, VideoIO.jl assumes that frame rates can only be integers. Many video capture devices do not have exactly integer frame rates, making it difficult to process their output with VideoIO.jl. I have therefore made simple modifications to the encoding code to allow rational frame rates.
=> Allow encoding with rational frame rates

src/ffmpeg/AVUtil/v56/LIBAVUTIL.jl, src/util.jl
The current code to access a member of a struct pointer uses a package function, `fieldposition`, that has identical functionality to a function provided in base, `fieldindex`. While this latter function is not exported, it is documented and will hopefully remain a part of Julia's API. I imagine that the base function is more performant than the implementation in `fieldposition`, which compares each field name to the target field name in order to find the position of a field. As such, I have replaced calls to `fieldposition` with calls to `Base.fieldindex`, and deleted the function `fieldposition`.
Additionally, when setting a member of a struct pointer, the current implementation calculates the pointer position, wraps it in a julia array with `unsafe_wrap`, and then sets the first …
=> Increase efficiency of accessing members of struct pointers

src/util.jl
As part of #250 I benchmarked the performance of `av_setfield`, and observed that it currently takes ~380 ns. While this is fast, it's not as fast as I would expect for what should boil down to a few machine instructions. This is primarily due to the seemingly inherent type instability of accessing a field by its name. However, upon further reflection, this didn't make sense to me, as this should happen every time you access a field in Julia (e.g. `foo.a` which is translated to `getproperty(foo, sym)`, which is in turn translated to `getfield(foo, sym)` where `sym = :a`). Unlike in the generic case, where you don't know ahead of time which field will be accessed, if the call occurs inside of a function, the field name is a constant which can be utilized by the compiler. I therefore …
=> Make accessing members of structs through pointers more efficient

.github/workflows/RunTests.yml, Project.toml, src/encoding.jl
Hoping to add hardware accelerated encoding, as per https://trac.ffmpeg.org/wiki/HWAccelIntro
Dependent on an updated FFMPEG_jll via https://github.com/JuliaPackaging/Yggdrasil/pull/1384 and https://github.com/JuliaIO/FFMPEG.jl/pull/32
=> Add optional nvidia hardware-accelerated h264_nvenc encoding

src/avio.jl
Two fields of `VideoReader`, `framerate` and `aspect_ratio`, are both of type `Rational`, an abstract type. In reality, the constructor of `VideoReader` sets both of these fields to be type `Rational{Cint}`. By changing the type definition to reflect that, it reduces type instability in code accessing `VideoReader` fields, while not restricting the generality of `VideoReader`.
=> Make some fields in `VideoReader` concrete types

src/avio.jl
In `VideoReader`'s constructor, `aspect_ratio` is either set to the aspect ratio from the codec context, which is converted into a `Rational{Cint}`, or instead `0 // 1` if the denominator is zero, which is a `Rational{Int}`. This causes unceccessary type instability, which can be fixed by instead making `aspect_ratio = Cint(0) // Cint(1)` if the denominator is zero.
=> Fix one instance of type instability within VideoReader

src/encoding.jl, test/avio.jl
In #249 the framerate arg in `prepareencoder` and `mux` was restricted to `Integer` or `Rational`, however floats can also be passed as the conversion into `Rational` will handle them.
That PR also introduced a breaking change that I missed as the type of the kwargs became more limited, and it was actually possible to pass floats, as long as they rounded to `Integer` successfully.
cc @galenlynch
=> Allow encode with float framerates via Rational conversion

src/avio.jl
Currently, the Julia compiler cannot infer the return type of `eof`. I am not
100% sure why it exhibits type instability, but we can at least assert that the
return type will be a `Bool`, and limit the spread of that type instability.
This type assertion will hopefully be removed at some point when the code is
made type stable.
=> Assert return type of `eof`

docs/src/reading.md, src/info.jl, test/avio.jl
There is currently no way to query a video container to determine the number of video frames that it contains, besides decoding the video and counting the frames. While this is the best you can do for some container formats, other container formats can report the number of frames without decoding each video frame. I have added a new function, `get_number_frames`, which will query the container and return the number of frames, if applicable, or return `nothing` otherwise. This function will not decode the video stream in order to determine the number of frames.
I have additionally added simple tests of this function, a documentation string, and added it to the docs.
=> Add utility function `get_number_frames`

docs/src/reading.md, src/VideoIO.jl, src/avio.jl, test/avio.jl
I have added an iterator interface to the `VideoReader` type, making collecting all frames of a video as simple as:
```julia
f = openvideo(fname)
imgs = collect(f)
```
The iterator returns a new array for each frame, as I think mutating the same array on subsequent calls to `iterate` would be surprising and lead to strange behavior when calling functions such as `collect`. Note that the VideoReader iterator is mutable, like Channel or Stateful iterators in Julia, and will resume iteration where it was last stopped, instead of at the beginning. I have added some text in the documentation explaining this behavior, and also added some tests.
=> Add iterator interface to VideoReader objects

src/info.jl
Candidate fix for #262 
@TheCedarPrince: If these tests pass, can you give this a go
=> Close file during path-based get_duration get_start_time get_time_duration

src/VideoIO.jl, src/avio.jl
`permuteddimsview` has been deprecated in ImageCore.jl, in favor of `PermutedDimsArray` in Base. I have replaced `permuteddimsview` with `PermutedDimsArray` in this package to avoid deprecation warnings.
=> Remove `permuteddimsview`, which is deprecated

src/avio.jl
Fixes #111 and enables frames to be grabbed from a webcam without transcoding. This is particularly useful when only luminance values are required and the transcoding to RGB is actually unhelpful. 
I use this within a Raspberry Pi computer vision system for control. As such, speed is important - without transcoding I can grab a frame in 1.5ms whereas with transcoding it takes 63.5ms.
The data is returned in a UInt8 array rather than a more specifically typed array but this seems to be in line with the original (unimplemented) intent. To interpret this data, the specific webcam pixel format needs to be known but that is relatively trivial (see `cam = VideoIO.opencamera(;transcode=false); cam.format` and compare against the `AVPixelFormat` values in `libavutil_h.jl`.
=> Add code for non-transcoded video streams

.github/workflows/RunTests.yml
@galenlynch I thought this might make your testing more manageable
=> Disable fail fast github actions CI

docs/src/writing.md, src/VideoIO.jl, src/avio.jl, src/avptr.jl, src/encoding.jl, src/frame_graph.jl, test/accuracy.jl, test/reading.jl, test/writing.jl, util/lossless_video_encoding_testing.jl
@galenlynch if we rename `container_settings`->`container_options` do we also want to:
change
```
container_settings::SettingsT = (;),
container_private_settings::SettingsT = (;),
encoder_settings::SettingsT = (;),
encoder_private_settings::SettingsT = (;),
```
to
```
container_options::OptionsT = (;),
container_private_options::OptionsT = (;),
encoder_options::OptionsT = (;),
encoder_private_options::OptionsT = (;),
```
Note `OptionsT`
=> Naming and settings fixes

docs/src/reading.md, src/VideoIO.jl, src/avio.jl, src/testvideos.jl, test/reading.jl
Adds a basic `load` function to load the entire video into memory as a framestack
```julia
VideoIO.load("video.mp4")
```
Along with the also non-exported `VideoIO.save`, these can be the functions we link to FileIO
=> add VideoIO.load function

CHANGELOG.md, docs/src/writing.md, src/VideoIO.jl, src/encoding.jl, test/writing.jl
master
```julia
open_video_out("video.mp4", first(framestack)) do writer
for i in eachindex(framestack)
append_encode_mux!(writer, framestack[i], i)
end
end
```
this PR
```julia
open_video_out("video.mp4", first(framestack)) do writer
for frame in framestack
write(writer, frame)
end
end
```
Given the index had to start at 0, and increment monotonically, we might as well do it internally
Edit: was `push!` now is `write`
=> append_encode_mux! -> Base.write, and simplify

.github/workflows/CI.yml, src/avio.jl, src/encoding.jl
I had assumed that ffmpeg/h.264 automatically handled multithreading, but it seems not to be the case.
The small change in this PR is based on https://stackoverflow.com/questions/43251612/ffmpeg-how-to-use-multithreading
I propose that the default is set to `Threads.nthreads()` but that users can tune it as they wish.
```julia
julia> function foo()
f = openvideo("vid.mp4")
i = 1
img = read(f)
i += 1 
while !eof(f)
read!(f, img)
i += 1
end
close(f)
@show i
end
julia> @time foo();
i = 1789
27.231079 seconds (1.91 k allocations: 9.032 MiB, 0.03% gc time)
```
Where `Threads.nthreads() == 16`
```julia
julia> @time foo();
i = 1789
3.339067 seconds (1.91 k allocations: 9.032 MiB)
```
Not much of an improvement in my case, but might be tunable for a given system
```julia
julia> imgstack = …
```
=> Enable adjustable codec multithreading

src/avio.jl, test/reading.jl
Tests the failure in #313 (this should fail on master)
Should be merged with the correct failure before #314
=> add RGB -> monochrome read test

src/avdictionary.jl
This PR addresses #341.
I compared both solutions proposed in the chat and found that `cconvert()` is preferred over `unsafe_convert()` as I assumed, so I implemented the solution for `cconvert()`.
I was not completely sure whether `convert()` is needed somewhere in the code - although I couldn't find any evidence in the code - so I kept it.
EDIT: added "not" in the phrase above...
=> fix error of `opencamera()`

src/avio.jl, src/frame_graph.jl
@galenlynch this appears to be a typo. Can you confirm?
Evidently our tests aren't covering this branch.
Fixes https://github.com/JuliaIO/VideoIO.jl/issues/313
=> Fix typo for bit_depth

.github/workflows/Documentation.yml, src/VideoIO.jl, src/avio.jl
Defers populating available cameras and identifying the default until the user requests cameras, which helps package load time.
Before
```
julia> @time using VideoIO
2.679612 seconds (3.20 M allocations: 237.017 MiB, 3.63% gc time, 34.81% compilation time)
```
This PR
```
julia> @time using VideoIO
2.183519 seconds (2.97 M allocations: 221.639 MiB, 3.81% gc time, 27.94% compilation time)
```
=> Lazy-load cameras to improve package load time

docs/src/index.md
Title for ARM platform notes says Platform Nodes. This PR fixes that typo.
=> Fix docs header typo

Project.toml, docs/src/reading.md, src/VideoIO.jl
`show_axis` & `scale_plot` no longer supported
fixes #354
=> update sample code to latest Makie API fix #354

src/avptr.jl
This causes a warning during precompilation
=> Remove unused type parameter in method signature

lib/libffmpeg.jl
The autoexport mechanism in `libffmpeg` is exporting literally _everything_, including over one thousand of totally useless names, like `Symbol("##meta#58")` which happens to be already defined in `VideoIO`, causing a clash.
=> Avoid exporting garbage from `libffmpeg`

src/avio.jl, src/testvideos.jl, test/reading.jl
See https://www.ffmpeg.org/doxygen/trunk/structAVCodecContext.html
- time_base
- ticks_per_frame
=> fix(): framerate miscalculate fps for some codecs

src/VideoIO.jl, src/avio.jl, src/deprecations.jl
- get_camera_devices doesn't seem to be using the ffmpeg argument
=> Remove need of redundant argument ffmpeg

test/reading.jl
Now that PNGFiles is fixed by https://github.com/JuliaIO/PNGFiles.jl/issues/74
The depwarns are an upstream issue https://github.com/JuliaIO/FFMPEG.jl/issues/57
ARMv8 CI seems unhappy but it's not clear if there's anything to fix here
=> Mark summarysize test as broken with todo (fixes nightly)

docs/src/writing.md
Without FileIO the example did not work for me so I'm under the impression that it's mandatory.
Without "using FileIO" the error message `ERROR: LoadError: UndefVarError: `load` not defined` occurred.
This is the outcome of the following [post](https://discourse.julialang.org/t/video-creation-example-does-not-work-to-naive-way/111888).
I also added the package "ImageIO.jl" before as (for me) implied in the post. But I don't know if this is relevant here.
Disclaimer: This is my first contribution to an open source project ever. So please let me know if there are more rules to follow for contribution.
=> Update writing.md: Add FileIO dependency
