JuliaIO/VideoIO.jl

.travis.yml, src/avio.jl, src/testvideos.jl, test/avio.jl
This fixes tests on v0.4.  Julia v0.5 is still broken.
=> Modernize travis, fix tests

deps/build.jl
Just rebases #67 to the current master.
=> Add ffmpeg package and library names for ubuntu 15.04 (Replaces / Fixes #67)

REQUIRE, src/avio.jl, src/ffmpeg/AVCodecs/src/AVCodecs.jl, src/ffmpeg/AVDevice/src/AVDevice.jl, src/ffmpeg/AVFilters/src/AVFilters.jl, src/ffmpeg/AVFormat/src/AVFormat.jl, src/ffmpeg/AVUtil/src/AVUtil.jl, src/ffmpeg/SWResample/src/SWResample.jl, src/ffmpeg/SWScale/src/SWScale.jl, src/init.jl, src/libav/AVCodecs/src/AVCodecs.jl, src/libav/AVDevice/src/AVDevice.jl, src/libav/AVFilters/src/AVFilters.jl, src/libav/AVFormat/src/AVFormat.jl, src/libav/AVUtil/src/AVUtil.jl, src/libav/SWScale/src/SWScale.jl, src/testvideos.jl, src/version.jl, test/avio.jl
allows installing the package elsewhere
=> use dirname(@__FILE__) instead of Pkg.dir

src/util.jl
=> fix for new pipe API

.travis.yml, appveyor.yml, deps/build.jl, src/avio.jl, src/util.jl, util/archive/wrap_libav.jl, util/wrap_libav_split.jl
Currently build completes without error, but `] test VideoIO` fails because ffmpeg isn't present in the VideoIO deps folder
=> Updating windows to ffmpeg 4.1 and link all handled lib versions

src/VideoIO.jl, src/avio.jl
* This is not really a performance critical part of the code, but
might as well fix it
=> Make `read_packet` a global constant

src/avio.jl, test/avio.jl
=> Fix memory leak #246

src/avio.jl, test/avio.jl
Commit eaf4dbc fixed a bug where FFMPEG's line size alignment requirements were not met, but in doing so unintentionally restricted the types of Julia arrays that would would work with VideoIO's `read!` from the original `VidArray = Union{PermutedArray,Array}` to just `PermutedArrays`. While the default return type of VideoIO's `read` is a `PermutedDimsArray`, this commit caused regular arrays to throw an error when used with `read!`, and in effect changed the (undocumented) API of `read!` between VideoIO versions v0.7.1 and v0.7.2. Furthermore, the fixed `read!` that respects FFMPEG's SIMD alignment requirements should work with either a normal `Array`, or instead a `PermutedDimsArrays` view of that array; the memory layout of both types of buffers are identical.
I have removed the line …
=> Allow read! to work with regular arrays, not just PermutedDimsArrays

src/VideoIO.jl, src/avio.jl
I find it helpful if the parent module has a brief API summary, so I don't have to visit the webpage or build the docs. That said, perhaps the demo is too much and I should move it elsewhere?
=> Add a couple of docstrings

docs/Project.toml, docs/make.jl, docs/src/index.md, docs/src/reading.md
The building of docs seems to have broken (again!)
=> Fixing docs

src/encoding.jl
`VideoEncoder` is only used by the old encoding workflow, so here I just removed it and all associated functions.
=> Remove VideoEncoder and associated functions

src/avio.jl
=> fix load args & kwargs splats

docs/src/reading.md, src/VideoIO.jl, src/avio.jl, src/testvideos.jl, test/reading.jl
=> Fix some missing framerate/width/height funcs. Fix Makie playback viewer

Project.toml
I think it's time we release v1.0.0
Any objections?
=> VideoIO v1.0.0

src/avframe_transfer.jl, test/writing.jl
When the source image is packed in the same way as the ffmpeg buffer, sending the data across can happen in one instruction, which may provide some speedup.
=> Fast encode path when image data layout matches ffmpeg buffer

.github/workflows/CI.yml, Project.toml, src/avio.jl
This was breaking package load, and wasn't noticed because I thought CI covered 1.6
=> Fix `@something` breakage on 1.6. Add 1.6 to CI

.JuliaFormatter.toml, .github/workflows/codeformat-pr.yml, docs/make.jl, gen/epilogue.jl, gen/generate.jl, gen/prologue.jl, gen/rewriter.jl, src/VideoIO.jl, src/avdictionary.jl, src/avframe_transfer.jl, src/avio.jl, src/avptr.jl, src/encoding.jl, src/frame_graph.jl, src/info.jl, src/testvideos.jl, src/util.jl, test/accuracy.jl, test/avptr.jl, test/bugs.jl, test/reading.jl, test/runtests.jl, test/utils.jl, test/writing.jl, util/lossless_video_encoding_testing.jl
I thought it would be worth conforming the formatting in the human-generated codebase via JuliaFormatter
This formats that code, and sets up a bot that formats any open PRs and opens PRs against that PR if any formatting fixes are found.
=> Formatting: apply JuliaFormatter and add formatter PR bot

docs/src/writing.md
=> Clarify documentation on lossless RGB

docs/src/writing.md
=> Fix lossless example URL

docs/src/writing.md
=> Add tip on using hyphenated parameters

docs/src/writing.md
=> Fix slow example

src/VideoIO.jl
=> Silence `libx264` during precompilation

src/VideoIO.jl
See https://github.com/JuliaIO/VideoIO.jl/pull/385
=> deprecate makie-based functions

Project.toml
=> Update ColorTypes to 0.12
